version: '3.8'

services:
  zookeeper:
    image: debezium/zookeeper:1.9
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - ./zookeeper/data:/zookeeper/data
      - ./zookeeper/log:/zookeeper/log
      - ./zookeeper/txns:/zookeeper/txns

  kafka:
    image: debezium/kafka:1.9
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - ./broker/data:/data
      - ./broker/logs:/logs

#  connect:
#    image: debezium/connect:1.9
#    hostname: connect
#    container_name: connect
#    ports:
#      - "8083:8083"
#    environment:
#      - GROUP_ID=1
#      - CONFIG_STORAGE_TOPIC=my_connect_configs
#      - OFFSET_STORAGE_TOPIC=my_connect_offsets
#      - STATUS_STORAGE_TOPIC=my_connect_statuses
#      - BOOTSTRAP_SERVER=kafka:9092
#    depends_on:
#      - kafka
#
#  postgres:
#    image: debezium/example-postgres:1.9
#    hostname: postgres
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
